version: '3.8'

services:
  # 1. SERVICIO DE DESARROLLO (Referenciado por devcontainer.json)
  dev:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: dev_container
    volumes:
      # Monta la carpeta raíz de VS Code en el workspace
      - ..:/workspaces/:cached 
    # Mapeo de puertos para el Hot Reload y ejecución de la API
    ports:
      - "5062:5062" # Asegúrate de mapear el puerto de tu API aquí también.
      - "5000:5000"
      - "5001:5001"
    command: sleep infinity # Mantiene el contenedor ejecutándose

  # 3. SERVICIO FRONTEND (NUEVO)
  frontend:
    image: mcr.microsoft.com/dotnet/sdk:9.0 # Puedes usar sdk para desarrollo o aspnet para producción
    container_name: blazor_frontend
    working_dir: /app
    volumes:
      # Monta la carpeta de tu proyecto Blazor dentro del contenedor
      - ./MiBlazorMudApp.Frontend:/app
    ports:
      # Mapea el puerto 5008 del contenedor al puerto 5008 de tu host
      - "5008:5008"
    # Comando para ejecutar el proyecto Blazor en el puerto 5008 y escuchar en 0.0.0.0
    command: dotnet run --project MiBlazorMudApp.Frontend.csproj --urls "http://0.0.0.0:5008"
    depends_on:
      - mssql # El frontend no depende realmente de la DB, pero es una buena práctica de orden.

  # 4. SERVICIO SQL SERVER
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "Admin_123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./sql-init:/docker-entrypoint-initdb.d

volumes:
  sqlserver-data: